group: travis_latest
dist: xenial
sudo: true

language: python

# don't build on tag pushes, since we created them!
if: tag IS blank

env:
  global:
    CACHE_NAME: coverage

stages:
  - name: test
    if: env(DO_RELEASE) != true
  - name: release

python:
  - "2.7"
  - "3.7"


install:
- "python --version"
- "curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python"
- "source $HOME/.poetry/env"
- "poetry install"
- "python env.py"

script:
- "pytest --cov playground -s test.py"
#- "git remote -v"
#- "git tag"
#- git config --global user.email "test@example.com"
#- git config --global user.name "Test User"
#- export GIT_TAG=$TRAVIS_BUILD_NUMBER-$TRAVIS_PYTHON_VERSION
#- git tag $GIT_TAG
#- git push --tags https://carthorse-cjw296:$GITHUB_TOKEN@github.com/cjw296/playground.git/


after_success:
  - codecov


jobs:
  include:
    - stage: release
      if: repo = cjw296/playground
      python: 3.7
      script:
      - "python github.py"
      - "python travis.py"
