version: 2.0

run_tests: &run_tests
    steps:
      - checkout
      - run:
          command: |
            curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
            source $HOME/.poetry/env
            poetry install
            poetry run pytest --cov playground -s test.py

jobs:
  "python-2.7":
    docker:
      - image: python:2.7
    <<: *run_tests

  "python-3.7":
    docker:
      - image: python:3.7
    <<: *run_tests

#  "coverage":
#    docker:
#      - image: python:3.7
#    steps:
#      - run:
#          command: |
#            pip install coverage
#            coverage combine
#            coverage report --show-missing --skip-covered --fail-under=100
#
workflows:
  version: 2
  build:
    jobs:
      - "python-2.7"
      - "python-3.7"
#      - "coverage":
#          requires:
#            - "python-2.7"
#            - "python-3.7"
