version: 2.1

orbs:
  playground: cjw296/playground-orb@dev

common: &common
  jobs:
    - playground/run-tests:
        name: python27
        image: python:2.7
    - playground/run-tests:
        name: python37
        image: python:3.7
    - playground/coverage:
        requires:
          - python27
          - python37
    - playground/release:
        requires:
          - playground/coverage
        filters:
          branches:
            only: master

workflows:
  push:
    <<: *common
  periodic:
    <<: *common
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
