version: 2.1

commands:
  install-poetry:
    steps:
      - run:
          name: "Install poetry"
          command: |
            curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
            source $HOME/.poetry/env
            echo 'export PATH=$HOME/.poetry/bin:$PATH' >> $BASH_ENV
  run-with-coverage:
    parameters:
      image:
        command: string
    steps:
      - run:
          name: "Run Tests"
          command: |
            python --version
            mkdir -p coverage_output
            export COVERAGE_FILE=coverage_output/.coverage.$CIRCLE_BUILD_NUM
            << parameters.command >>
      - persist_to_workspace:
          root: coverage_output
          paths:
            - .coverage.*


jobs:
  run-tests:
    parameters:
      image:
        type: string
    docker:
      - image: << parameters.image >>
    steps:
      - checkout
      - install-poetry
      - run:
          name: "Install Project"
          command: poetry install
      - run-with-coverage:
          command: poetry run pytest --cov playground -s test.py

  check-coverage:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - attach_workspace:
          at: coverage_output
      - run:
          name: "Check coverage"
          command: |
            pip install coverage
            coverage combine coverage_output/
            coverage report --show-missing --skip-covered --fail-under=100

  release-when-version-changes:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - install-poetry
      - run:
          name: "Release"
          command: |
            poetry --help
#            pip install carthorse
#            carthorse

common: &common
  jobs:
    - run-tests:
        name: python27
        image: python:2.7
    - run-tests:
        name: python37
        image: python:3.7
    - check-coverage:
        requires:
          - python27
          - python37
    - release-when-version-changes:
        requires:
          - check-coverage
        filters:
          branches:
            only: master

workflows:
  push:
    <<: *common
  periodic:
    <<: *common
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
