version: 2.1

orbs:
  playground: cjw296/playground-orb@dev:first

common: &common
  jobs:

    - playground/run-tests:
        name: python27
        image: circleci/python:2.7
        command: poetry run pytest --cov playground -s test.py
    - playground/run-tests:
        name: python37
        image: circleci/python:3.7
        command: poetry run pytest --cov playground -s test.py

    - playground/coverage:
        name: coverage
        requires:
          - python27
          - python37

    - playground/release:
        name: release
        requires:
          - coverage
        filters:
          branches:
            only: master

workflows:
  push:
    <<: *common
  periodic:
    <<: *common
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
